name: Deploy with OIDC

on:
  pull_request:
    paths:
      - 'components/oidc-example/**'

permissions:
  id-token: write
  contents: read

jobs:
  oidc_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ vars.AWS_DEPLOY_ROLE }}
          aws-region: "ap-northeast-1"
      - name:  Copy to s3
        run: |
          aws --region 'ap-northeast-1' s3 cp components/oidc-example/README.md s3://thaim-oidc-example-resource
